<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b186e404-7ae4-40c1-b3f0-d068aa20d674</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Serilog.Sinks" Version="9.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServicosFinanceiros.Application\ServicosFinanceiros.Application.csproj" />
    <ProjectReference Include="..\ServicosFinanceiros.Infrastructure\ServicosFinanceiros.Infrastructure.csproj" />
  </ItemGroup>

</Project>
